FROM ubuntu:14.04
MAINTAINER Alejandro Vera De Juan <xafilox@gmail.com>

#Better to use bash instead of sh
RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh

#Install Apache2 adn PHP5
RUN apt-get -qq update && \
	apt-get -qq -y install \
		apache2 \
		php5 \
		curl \
		php5-mcrypt \
		php5-json

#Configure PHP
RUN php5enmod mcrypt
RUN php5enmod json

#Configure apache	
RUN /usr/sbin/a2enmod rewrite
RUN /usr/sbin/a2enmod ssl
RUN /usr/sbin/a2ensite default-ssl
RUN sed -i 's/\/var\/www\/html/\/var\/www\/html\/public/g' /etc/apache2/sites-available/*.conf

#Install composer
RUN /usr/bin/curl -sS https://getcomposer.org/installer |/usr/bin/php
RUN /bin/mv composer.phar /usr/local/bin/composer
RUN chmod +x /usr/local/bin/composer

#Copy repository
RUN rm -rf /var/www/html/*
COPY . /var/www/html
RUN mv /var/www/html/.env.example /var/www/html/.env

#Install vendor dependencies of laravel
RUN cd /var/www/html && \
    composer install -q -n && \
    chown -R www-data:www-data /var/www/

#Install mysql
RUN source /var/www/html/.env && echo "mysql-server mysql-server/root_password password $DB_PASSWORD" | debconf-set-selections
RUN source /var/www/html/.env && echo "mysql-server mysql-server/root_password_again password $DB_PASSWORD" | debconf-set-selections
RUN apt-get -qq -y install \
		mysql-server-5.6 \
		php5-mysqlnd

#Initialize the database (create and fill with laravel migrations)
RUN source /var/www/html/.env && \
    service mysql start && \
    mysql -uroot --password=${DB_PASSWORD} -e "CREATE USER '${DB_USERNAME}'@'%' IDENTIFIED BY '${DB_PASSWORD}'; \
    GRANT ALL PRIVILEGES ON ${DB_DATABASE}.* TO '${DB_USERNAME}'@'%' WITH GRANT OPTION; \
    CREATE DATABASE ${DB_DATABASE};" && \
    cd /var/www/html && \
    php artisan migrate --force --seed

#Install phpmyadmin
RUN source /var/www/html/.env && \
    apt-get -qq -y install pwgen && \
    AUTOGENERATED_PASS=`pwgen -c -1 20` && \
    echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections && \
    echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections && \
    echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections && \
    echo "phpmyadmin phpmyadmin/mysql/admin-pass password ${DB_PASSWORD}" | debconf-set-selections && \
    echo "phpmyadmin phpmyadmin/mysql/app-pass password ${AUTOGENERATED_PASS}" |debconf-set-selections && \
    echo "phpmyadmin phpmyadmin/app-password-confirm password ${AUTOGENERATED_PASS}" | debconf-set-selections && \
    service mysql start && \
    apt-get -qq -y install phpmyadmin && \
    apt-get -qq -y autoremove && \
    apt-get -qq clean


# Ports
EXPOSE 80 443

#Share mysql data directory
VOLUME ["/var/lib/mysql"]

CMD service apache2 stop; \
    echo "Starting apache"; \
    service apache2 restart; \
    echo "Starting mysql"; \
    mysqld_safe